### Add Requirement Success
@checklistId=1d92c485-16ef-4606-b44f-c1ee0abf8ae7
POST {{host}}/api/checklists/{{checklistId}}/requirements
Content-Type: application/json

{
    "title": "Requirement 1",
    "text": "Text 1"
}

### Add Requirement Error
POST {{host}}/api/checklists/{{checklistId}}/requirements
Content-Type: application/json

{
    "title": "",
    "text": "Text 1"
}