### Add Requirement Success
@checklistId=a233772d-3f13-457d-ad5a-b87c6e416fc5
POST {{host}}/api/checklists/{{checklistId}}/requirements
Content-Type: application/json

{
    "title": "Requirement 1",
    "text": "Text 1"
}

### Add Requirement Error
POST {{host}}/api/checklists/{{checklistId}}/requirements
Content-Type: application/json

{
    "title": "",
    "text": "Text 1"
}