### Set complied state of a requirement to true
@requirementId=e5dd3aaa-ccdc-466e-b752-fe7c5ffbdf91
PATCH {{host}}/api/requirements/{{requirementId}}
Content-Type: application/json

{
    "isComplied": true
}

### Set complied state of a requirement to false
PATCH {{host}}/api/requirements/{{requirementId}}
Content-Type: application/json

{
    "isComplied": false
}