### Set complied state of a requirement to true
@requirementId=8a4e875a-3b23-47c5-af3c-c5ba21646e0a
PATCH {{host}}/api/requirements/{{requirementId}}
Content-Type: application/json

{
    "isComplied": true
}

### Set complied state of a requirement to false
PATCH {{host}}/api/requirements/{{requirementId}}
Content-Type: application/json

{
    "isComplied": false
}